### ISSUE TITLE
JOSS paper references

### ISSUE THREAD

**Issue by samhforbes** [mortonne/psifr#2]
Hi @mortonne , the paper is also really well done. Minor issue here, please include DOIs for Murdock 1962 and Kahana 1996.

Another thing (and I want to point this is *entirely* up to you, is since some of the visualisations are a real strength of this package, you may wish to include one such plot in the paper as it gives the reader a taste of what the package can do, but as I say, that's entirely up to you.

**Comment by mortonne** [comment]
Thanks, this is a great suggestion. I've added plots of recall by serial position, both on average and for individual participants. I've also added an example of a raster plot, to highlight a type of plot I haven't seen done in similar packages.

I have also added DOIs for those references.
